name: ci

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.21"
          - "1.22"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go (${{ matrix.go }})
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: instal protoc-gen-gogo
        run: go get github.com/gogo/protobuf/protoc-gen-gogo

      - name: Verify pb.go is up to date (${{ matrix.go }})
        run: make verify-pb-go-up-to-date

      - name: Test pb.go (${{ matrix.go }})
        run: make test
